# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duaf9877/FlyRank-AI-ML-Internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [1]:
from google.colab import userdata
hf_token = userdata.get('HF_TOKEN')

One row = one content item, for one client, on one report date —
a (client_id, content_id, report_date) row from fact_content_daily_performance,
filtered to month = '2026-03' (mid-panel month; the final month, June 2026,
is a sealed test window and is never used to develop label logic).

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

**Table(s):** fact_content_daily_performance (joined across month=2026-02 and
month=2026-03 partitions), joined to dim_content (content metadata, keyed on
content_hash_id) and filtered using dim_clients where relevant for history checks.

**Predict/rank:** a decline-risk proxy label built by comparing March's
gsc_clicks total to February's gsc_clicks total, at the (client_hash_id,
content_hash_id) grain — used to rank content items for review priority.

| Bucket | Fields |
|---|---|
| Feature | gsc_avg_position, impressions_march, sessions_march, word_count, days_since_last_update |
| Label (proxy) | is_declining — derived flag: clicks_march < 0.8 * clicks_feb |
| Context | client_hash_id, content_hash_id, report_date (identifiers only, never features) |
| Excluded | clicks_march as a *feature* — excluded because it's literally the value used to define is_declining; using it as a predictor would leak the label directly (clicks_feb is safe to use since it's the prior month, not the outcome window) |

Once that's in and the cells run clean, Part 1 is done — move to the verification
queries, feature frame, and leakage trap next (Part 3).

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [3]:
import duckdb
from google.colab import userdata

hf_token = userdata.get('HF_TOKEN')

con = duckdb.connect()
con.execute("INSTALL httpfs; LOAD httpfs;")

con.execute(f"""
    CREATE SECRET hf_token (
        TYPE HUGGINGFACE,
        TOKEN '{hf_token}'
    );
""")

BASE = "hf://datasets/FlyRank/internship-warehouse"

In [6]:
from huggingface_hub import HfApi

api = HfApi(token=hf_token)
files = api.list_repo_files("FlyRank/internship-warehouse", repo_type="dataset")

for f in files:
    print(f)

.gitattributes
README.md
dim_clients.parquet
dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet
fact_content_query_90d.parquet

In [7]:
BASE = "hf://datasets/FlyRank/internship-warehouse"

# Check dim_clients columns
con.execute(f"DESCRIBE SELECT * FROM read_parquet('{BASE}/dim_clients.parquet')").df()

           column_name column_type null   key default extra
0       client_hash_id     VARCHAR  YES  None    None  None
1            is_active     BOOLEAN  YES  None    None  None
2       has_gsc_access     BOOLEAN  YES  None    None  None
3       has_ga4_access     BOOLEAN  YES  None    None  None
4       access_profile     VARCHAR  YES  None    None  None
5  client_created_date        DATE  YES  None    None  None
6  client_updated_date        DATE  YES  None    None  None
7       gsc_data_start        DATE  YES  None    None  None
8       ga4_data_start        DATE  YES  None    None  None

In [9]:
test = con.execute(f"DESCRIBE SELECT * FROM read_parquet('{BASE}/dim_content.parquet')").df()
test

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

In [17]:
grain_check = con.execute(f"""
    SELECT report_date, client_hash_id, content_hash_id, COUNT(*) AS n
    FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-03/data_0.parquet')
    GROUP BY report_date, client_hash_id, content_hash_id
    HAVING COUNT(*) > 1
    LIMIT 5
""").df()

print("Rows violating grain (should be empty):")
grain_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Rows violating grain (should be empty):

Empty DataFrame
Columns: [report_date, client_hash_id, content_hash_id, n]
Index: []

In [27]:
grain_check_content = con.execute(f"""
    SELECT content_hash_id, COUNT(*) AS n
    FROM read_parquet('{BASE}/dim_content.parquet')
    GROUP BY content_hash_id
    HAVING COUNT(*) > 1
    LIMIT 5
""").df()

grain_check_content

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [content_hash_id, n]
Index: []

In [28]:
features_df = con.execute(f"""
    WITH march AS (
        SELECT
            client_hash_id,
            content_hash_id,
            AVG(gsc_avg_position) AS gsc_avg_position,
            SUM(gsc_clicks) AS clicks_march,
            SUM(gsc_impressions) AS impressions_march,
            SUM(ga4_sessions) AS sessions_march
        FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-03/data_0.parquet')
        WHERE gsc_data_available IS TRUE
        GROUP BY client_hash_id, content_hash_id
    ),
    february AS (
        SELECT
            client_hash_id,
            content_hash_id,
            SUM(gsc_clicks) AS clicks_feb
        FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-02/data_0.parquet')
        WHERE gsc_data_available IS TRUE
        GROUP BY client_hash_id, content_hash_id
    ),
    content_meta AS (
        SELECT
            content_hash_id,
            ANY_VALUE(word_count) AS word_count,
            ANY_VALUE(DATE_DIFF('day', content_created_date, DATE '2026-03-31')) AS content_age_days,
            ANY_VALUE(DATE_DIFF('day', content_updated_date, DATE '2026-03-31')) AS days_since_last_update
        FROM read_parquet('{BASE}/dim_content.parquet')
        GROUP BY content_hash_id
    )
    SELECT
        m.client_hash_id,
        m.content_hash_id,
        m.gsc_avg_position,
        m.impressions_march,
        m.sessions_march,
        c.word_count,
        c.days_since_last_update,
        f.clicks_feb,
        m.clicks_march
    FROM march m
    JOIN february f USING (client_hash_id, content_hash_id)
    JOIN content_meta c USING (content_hash_id)
""").df()

features_df.shape

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

(134238, 9)

In [29]:
features_df['is_declining'] = (
    features_df['clicks_march'] < 0.8 * features_df['clicks_feb']
).astype(int)

honest_features = ['gsc_avg_position', 'impressions_march', 'sessions_march',
                    'word_count', 'days_since_last_update']

In [18]:
counts = con.execute(f"""
    SELECT
        COUNT(*) AS row_count,
        MIN(report_date) AS min_date,
        MAX(report_date) AS max_date,
        COUNT(DISTINCT client_hash_id) AS n_clients,
        COUNT(DISTINCT content_hash_id) AS n_content
    FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-03/data_0.parquet')
""").df()

counts

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   row_count   min_date   max_date  n_clients  n_content
0    9841378 2026-03-01 2026-03-31         55     331437

In [30]:
availability = con.execute(f"""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(*) FILTER (WHERE gsc_data_available IS TRUE) AS available_rows
    FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-03/data_0.parquet')
""").df()

availability['pct_available'] = round(
    100 * availability['available_rows'] / availability['total_rows'], 1
)
availability

   total_rows  available_rows  pct_available
0     9841378         3611061           36.7

In [31]:
con.execute(f"""
    DESCRIBE SELECT * FROM read_parquet('{BASE}/dim_content.parquet')
""").df()

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

In [32]:
con.execute(f"""
    DESCRIBE SELECT * FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-03/data_0.parquet')
""").df()

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

In [33]:
features_df = con.execute(f"""
    WITH march AS (
        SELECT
            client_hash_id,
            content_hash_id,
            AVG(gsc_avg_position) AS gsc_avg_position,
            SUM(gsc_clicks) AS clicks_march,
            SUM(gsc_impressions) AS impressions_march,
            SUM(ga4_sessions) AS sessions_march
        FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-03/data_0.parquet')
        WHERE gsc_data_available IS TRUE
        GROUP BY client_hash_id, content_hash_id
    ),
    february AS (
        SELECT
            client_hash_id,
            content_hash_id,
            SUM(gsc_clicks) AS clicks_feb
        FROM read_parquet('{BASE}/fact_content_daily_performance/month=2026-02/data_0.parquet')
        WHERE gsc_data_available IS TRUE
        GROUP BY client_hash_id, content_hash_id
    )
    SELECT
        m.client_hash_id,
        m.content_hash_id,
        m.gsc_avg_position,
        m.impressions_march,
        m.sessions_march,
        f.clicks_feb,
        m.clicks_march   -- kept ONLY to build the label, not as a feature
    FROM march m
    JOIN february f USING (client_hash_id, content_hash_id)
""").df()

features_df.shape

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

(134238, 7)

In [34]:
features_df['is_declining'] = (
    features_df['clicks_march'] < 0.8 * features_df['clicks_feb']
).astype(int)

features_df['is_declining'].value_counts()

is_declining
0    112546
1     21692
Name: count, dtype: int64

**Five features (all knowable before the decision moment):**

1. `gsc_avg_position` — knowable at decision time because it's the ranking position observed as of report_date, before any refresh decision is made.
2. `clicks_prev_30d` — knowable because it's the prior 30-day window, fully in the past relative to the decision.
3. `impressions_prev_30d` — same reasoning: prior-window, already observed.
4. `content_age_days` — knowable because it's a static fact about the content, computed from publish date.
5. `days_since_last_update` — knowable because it only depends on the content's edit history up to today.

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

honest_features = ['gsc_avg_position', 'impressions_march', 'sessions_march']

X = features_df[honest_features].fillna(0)
y = features_df['is_declining']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = LogisticRegression(max_iter=1000).fit(X_train, y_train)
honest_score = roc_auc_score(y_test, model.predict_proba(X_test)[:,1])
print("Honest AUC:", round(honest_score, 3))

Honest AUC: 0.551

In [37]:
leaky_features = honest_features + ['clicks_march', 'clicks_feb']

X_leak = features_df[leaky_features].fillna(0)
X_train, X_test, y_train, y_test = train_test_split(X_leak, y, test_size=0.3, random_state=42)
model_leak = LogisticRegression(max_iter=1000).fit(X_train, y_train)
leaky_score = roc_auc_score(y_test, model_leak.predict_proba(X_test)[:,1])
print("Leaky AUC:", round(leaky_score, 3))

Leaky AUC: 1.0

## The leakage trap

`is_declining` is defined as `clicks_march < 0.8 * clicks_feb` — a deterministic
function of exactly two numbers. When both `clicks_march` and `clicks_feb` are
included as features, the model can reconstruct the label rule exactly:

- **Honest model** (5 features only: gsc_avg_position, impressions_march,
  sessions_march, word_count, days_since_last_update): **AUC = 0.551**
- **Leaky model** (honest features + clicks_march + clicks_feb): **AUC = 1.0**

The jump from 0.551 to 1.0 isn't the model learning a better pattern — it's the
model being handed the exact inputs used to compute the label, so it can just
replay the arithmetic. This is the leakage lesson from notebook 02, reproduced
here on real warehouse data: the moment a feature (or pair of features) can
recompute the label, the "signal" is fake.

Removing `clicks_march` and `clicks_feb` from the feature set restores the
honest, defensible number: **AUC ≈ 0.551**. That's the real result — a model
barely better than chance, using only information genuinely available before
the decision moment. That's the number to report, not 1.0.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

  ## Data limits
- Causal effect of a refresh can't be shown — only correlation between
  signals and decline.
- History depth varies by client (dim_clients.gsc_data_start differs),
  so days_since_last_update isn't fully comparable across clients without
  checking that first.
- GA4-only rows before a client's ga4 start date may be zero-filled
  placeholders, not real zero engagement — filtered here via gsc_data_available,
  but GA4-specific analysis would need client_has_ga4 checked too.
- Comparing exactly two months (Feb vs March) is a short window — a single
  bad or good month could look like a trend when it's noise.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.